---

- name: A playbook to DL images and UL to OS Glance
  hosts: localhost
  connection: local

  vars: 
    img_to_dl: " https://cloud-images.ubuntu.com/focal/20200322/focal-server-cloudimg-amd64-disk-kvm.img"
    ansible_python_interpreter: "/usr/bin/python"


  tasks: 
     
    # create a temp forlder to download to. 
     
    - name: download the image "{{ img_to_dl }}"
      get_url:
        url: "{{ img_to_dl }}"
        dest: /home/centos/ans

    #upload to OS Glance
    - name: upload the image "{{ img_to_dl }}"
      os_image: 
        cloud: alta3cloud
        name: cirros
        container_format: bare
        disk_format: qcow2
        state: present
        filename: cirros-0.3.0-x86_64-disk-img
        kernel: cirros-vmlinuz
        ramdisk: cirros-initrd
        properties:
          cpu_arch: x86_64
          distro: ubuntu

    # determine if checksum on upload matches what we expected
