---

     
    # create a temp forlder to download to. 
    - name: Create a temp folder to DL to 
      file: 
        state: directory
        path: "{{ tempdir }}"
 
    - name: download the image "{{ img_to_dl }}"
      get_url:
        url: "{{ img_to_dl }}"
        dest: "{{ tempdir }}"

    #upload to OS Glance
    - name: upload the image "{{ img_to_dl }}"
      os_image: 
        cloud: alta3cloud
        name: "{{ imgdate }}-{{ imgname.split('.')[0] }}"
        container_format: bare
        disk_format: qcow2
        state: present
        filename: "{{ tempdir }}{{ imgname }}"
        kernel: cirros-vmlinuz
        ramdisk: cirros-initrd
        properties:
          cpu_arch: x86_64
          distro: ubuntu

    # determine if checksum on upload matches what we expecte
    #
    # delete thetemp folder containing the image
    
    - name: delete file from the temp folder
      file:
        state: absent
        path: "{{ tempdir }}"
